name: PerMession
version: 1.0
main: org.mocraft.PerMession
softdepend: ["GroupManager", "PermissionsEx"]
commands:
      perme:
        description: Provide a more convience way to take back permission/commands.
        usage: |
               Unly Operator can use command.
               <period> in seconds.
               <command> with one single line command without slash(/)
               /<command> help - Plugin's Help.
               /<command> dur|duration <period> <command> - Let system after <period> execute command.
               /<command> dur-refelct|duration-refelct <peroid> <command> - Let system after <period> execute refelct-command.