name: PerMession
version: 1.0
main: org.mocraft.PerMession
depend: [GroupManager]
commands:
      perme:
        description: Count donw to cancel a Player's permission/group
        usage: Only Operator can use this command, /per <minutes> <commands>